import {WebPageAdapter,type WebConversationState} from '../web-page.js'

/** Qwen Web 页面适配器：只通过可见页面 DOM/CDP 操作，不调用 Qwen 私有 HTTP API。 */
export class QwenPage extends WebPageAdapter{
 expectedHost(){return 'chat.qwen.ai'}
 async isLoggedIn(){return this.cdp.evaluate<boolean>(`(()=>!!document.querySelector('textarea,[contenteditable="true"]') && !/登录|log in|sign in/i.test(document.body?.innerText||''))()`)}
 async getConversationState():Promise<WebConversationState>{return this.cdp.evaluate<WebConversationState>(`(()=>({url:location.href,conversationId:(location.pathname.match(/(?:chat|conversation|c)\\/([a-zA-Z0-9_-]+)/)||[])[1],ready:!!document.querySelector('textarea,[contenteditable="true"]'),changed:false}))()`)}
 async sendMessage(text:string){await this.cdp.evaluate<void>(`(()=>{const el=document.querySelector('textarea,[contenteditable="true"]');if(!el)throw new Error('PAGE_CHANGED: Qwen 输入框未找到');el.focus();if(el instanceof HTMLTextAreaElement){const s=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')?.set;s?.call(el,${JSON.stringify(text)});el.dispatchEvent(new Event('input',{bubbles:true}))}else{el.textContent=${JSON.stringify(text)};el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:${JSON.stringify(text)}}))}const b=[...document.querySelectorAll('button')].find(x=>/发送|send|提交/i.test(x.textContent||'')&&!x.disabled);if(b)b.click();else el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true}))})()`)}
 async readAnswer(previous:string){return this.cdp.evaluate<string>(`(()=>{const p=${JSON.stringify(previous)};const selectors=['[data-message-author-role="assistant"]','.message-content','.markdown-body','main article'];const nodes=selectors.flatMap(s=>[...document.querySelectorAll(s)]);const a=nodes.map(x=>(x.innerText||'').trim()).filter(x=>x&&x!==p);return a.at(-1)||''})()`)}
 async isGenerating(){return this.cdp.evaluate<boolean>(`(()=>[...document.querySelectorAll('button')].some(b=>/停止|stop|中止/i.test(b.textContent||'')))()`)}
 async detectError(){return this.cdp.evaluate<{code:string;message:string}|null>(`(()=>{const t=document.body?.innerText||'';if(/登录|log in|sign in|注册|sign up/i.test(t)&&!document.querySelector('textarea,[contenteditable="true"]'))return {code:'LOGIN_REQUIRED',message:'Qwen 需要登录'};if(/额度|usage limit|quota|limit reached/i.test(t))return {code:'QUOTA_EXCEEDED',message:'当前 Qwen 账号达到使用限制'};if(/频繁|too many|rate limit/i.test(t))return {code:'RATE_LIMITED',message:'请求过于频繁'};if(/服务异常|service unavailable|temporarily unavailable|网络错误/i.test(t))return {code:'SERVICE_UNAVAILABLE',message:'Qwen Web 服务暂时不可用'};return null})()`) }
}